### ISSUE TITLE
Can't build without deleting the build file in the root folder

### ISSUE THREAD

**Issue by hayschan** [radiosound-com/makerfabs-parallel-tft-lvgl-lgfx#4]
I cloned the repo and tried to build the project with ESP-IDF.

I keep getting "FileExistsError" as there is already a build file in the root file. As `idf.py` tries to create a "build" folder under root `./build`, this clashes with the existing build file in the root repo, which is also `./build`.

To build the project, I had to delete the existing build file.

**Comment by ftab** [comment]
Sorry about that. It's my weird scheme for being able to build with two separate build directories existing simultaneously (since this screen has an S2 version and an S3 version and I was tired of doing full rebuilds every time to switch back and forth).

You are free to delete those scripts and build the normal idf.py way.
